### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hrbrmstr** [hrbrmstr/terminator#1]
- [ ] ggplot2 Stat/Geom?
- [ ] generate sf/sp objects?
- [ ] create built-in animator function based on magick?

Pile on requests!
